server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.226.134
      database: spitdb
  jpa:
    show-sql: true
  redis:
    host: 192.168.226.134